# Generated by Django 5.2.4 on 2025-07-07 14:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='year',
            field=models.PositiveIntegerField(default=2025, help_text='Year the project was completed', validators=[django.core.validators.MinValueValidator(2000), django.core.validators.MaxValueValidator(2026)]),
        ),
    ]
